---
kind: Service
apiVersion: v1
metadata:
  name: spring-boot-hello
  namespace: flux
spec:
  type: LoadBalancer
  selector:
    app: spring-boot-hell
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
